---
name: Prueba Mejoras de Objetos
locale: es
type: learning
beta: false
teacher_info: ''
language: ruby
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 7
- 8
- 10
- 11
- 12
- 13
- 14
- 15
- 16
private: false
