---
locale: es
tags: []
layout: input_right
editor: code
type: problem
extra_visible: false
language: gobstones
teacher_info: ''
manual_evaluation: false
choices: []
name: Reemplazo de Un ejercicio sin precedentes
